project:
  type: website

website:
  title: "FELICIA NGUYEN"
  favicon: static-content/logo/logo-32x32.png
  navbar:
    logo: static-content/logo/logo.svg
    right:
      - href: about.qmd
        text: ABOUT
      - href: research/index.qmd
        text: RESEARCH
      - href: blog/index.qmd
        text: BLOG       
      #- href: teaching/index.qmd
      #  text: Teaching
      - href: CV/index.qmd
        text: CV
    toggle-position: "right"
  page-footer:
    left: "From Atlanta with 💖"
    center: © 2025  &middot; Created with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) .
    right:
      - href: https://github.com/fphng
        icon: github    
format:
  html:
    theme: 
      - Pulse
      - custom-theme.scss 
    toc: true

editor: visual


